ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS status VARCHAR(255) DEFAULT 'ACTIVE';

UPDATE users
SET status = 'ACTIVE'
WHERE status IS NULL;

ALTER TABLE IF EXISTS users
    ALTER COLUMN status SET DEFAULT 'ACTIVE',
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

UPDATE users
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE IF EXISTS users
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN created_at SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (email);
