spring:
  application:
    name: backend
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

stripe:
  enabled: true
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  account-id: ${STRIPE_ACCOUNT_ID:}
  api-version: ${STRIPE_API_VERSION:}
